# Generated by Django 4.1.7 on 2023-03-28 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JerryApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorydb',
            name='Description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
