# Generated by Django 4.1.7 on 2023-05-12 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0002_userdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartdb',
            name='User',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
